#!/usr/bin/env bash

gem install --conservative sass
wget --no-clobber --output-document=bulma.zip https://github.com/jgthms/bulma/releases/download/0.9.3/bulma-0.9.3.zip
unzip -u bulma.zip

wget --no-clobber --output-document=fontawesome.zip https://use.fontawesome.com/releases/v6.0.0/fontawesome-free-6.0.0-web.zip
unzip -u fontawesome.zip
mv fontawesome-free* fontawesome

cat << EOT > bulma.scss
@charset "utf-8";

\$warning: #ff6c0e;
\$fa-font-path: "fonts";

@import "bulma/bulma.sass";
@import "./_includes/highlight.scss";
@import "./fontawesome/scss/fontawesome.scss";
@import "./fontawesome/scss/solid.scss";
@import "./fontawesome/scss/brands.scss";

.content ul, .content ol {
   list-style-position: inside;
}
.content img.center{
  display: block;
  margin: 0 auto;
}

#menu-switch {
 display: none;
}
#menu-switch:checked + .navbar-brand .navbar-burger span:nth-child(1) {
  transform: translateY(5px) rotate(45deg);
}
#menu-switch:checked + .navbar-brand .navbar-burger span:nth-child(2) {
  opacity: 0;
}
#menu-switch:checked + .navbar-brand .navbar-burger span:nth-child(3) {
  transform: translateY(-5px) rotate(-45deg);
}
#menu-switch:checked ~ .navbar-menu{
 display: block;
}
EOT

sass --sourcemap=none \
     --style compressed \
     bulma.scss:style.css

rm -rf fonts
mv fontawesome/webfonts fonts
rm -rf bulma* .sass-cache fontawesome*
