#!/usr/bin/env bash

xlog \
--sitename "Emad Elsaid" \
--index=Home \
--gpg=A9835BF728B3C71784FE538C5D33E3F3A9937BAD \
--custom_head=header.html \
--sitemap.domain=www.emadelsaid.com \
--activitypub.domain=www.emadelsaid.com \
--activitypub.username=Emad \
--activitypub.summary="A Software Engineer. Ruby Golang. 🇪🇬 Egyptian 📷 Youtuber 🎮 Casual gamer and 🚀 Sci-Fi addict. My opinions are my own" \
--og.domain=www.emadelsaid.com \
--twitter.username=@emad__elsaid \
--github.repo=https://github.com/emad-elsaid/emad-elsaid.github.io \
--rss.domain=www.emadelsaid.com \
--rss.description="A Software Engineer. Ruby Golang. 🇪🇬 Egyptian 📷 Youtuber 🎮 Casual gamer and 🚀 Sci-Fi addict. My opinions are my own"
